services:
  - type: web
    name: fooder-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma db push --skip-generate
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_PUBLIC_BASE_URL
        sync: false
